"""initial

Revision ID: 15f5295adf12
Revises: 2cf35f085d25
Create Date: 2026-04-13 20:44:46.922851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '15f5295adf12'
down_revision: Union[str, None] = '2cf35f085d25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
